# Generated by Django 4.0.4 on 2022-04-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='inventory_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
